# settings.py

# TrueMail verify mail
API_KEY_TRUEMAIL = "YOUR_KEY"
API_URL_TRUEMAIL = "YOUR_URL"

# Temp Mail verify script
API_KEY_TEMPMAIL = "YOUR_KEY"
API_URL_TEMPMAIL = "YOUR_URL"
API_HOST_TEMPMAIL = "YOUR_HOST"
